global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'vectorhub'
    static_configs:
      - targets: ['vectorhub:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: 
        - 'redis-0:6379'
        - 'redis-1:6379'
        - 'redis-2:6379'
        - 'redis-3:6379'